package com.example.util

enum class AppLanguage(val code: String, val nativeName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिंदी"),
    GUJARATI("gu", "ગુજરાતી"),
    MARATHI("mr", "मराठी"),
    TAMIL("ta", "தமிழ்"),
    SPANISH("es", "Español"),
    PORTUGUESE("pt", "Português"),
    FRENCH("fr", "Français"),
    GERMAN("de", "Deutsch"),
    ARABIC("ar", "العربية"),
    INDONESIAN("id", "Bahasa Indonesia"),
    RUSSIAN("ru", "Русский"),
    TURKISH("tr", "Türkçe");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return values().find { it.code == code } ?: ENGLISH
        }
    }
}

object Localization {
    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "splash_title" to "Downloading Status Saver 2026",
            "splash_loading" to "Preparing Media Engine...",
            "welcome_title" to "Status Saver for WhatsApp",
            "welcome_desc" to "Save WhatsApp images and videos instantly.",
            "btn_next" to "Next",
            "btn_skip" to "Skip",
            "lang_title" to "Select Language",
            "btn_continue" to "Continue",
            "onboarding_title" to "Save in 3 Simple Steps",
            "onboarding_step1_title" to "1. Open WhatsApp",
            "onboarding_step1_desc" to "Open WhatsApp or WhatsApp Business as usual.",
            "onboarding_step2_title" to "2. Watch the Status",
            "onboarding_step2_desc" to "Watch the full image or video story you want to save.",
            "onboarding_step3_title" to "3. Save from the App",
            "onboarding_step3_desc" to "Come back here and download it safely with a single tap.",
            "btn_get_started" to "Get Started",
            "tab_images" to "Images",
            "tab_videos" to "Videos",
            "nav_home" to "Home",
            "nav_downloads" to "Downloads",
            "nav_settings" to "Settings",
            "search_hint" to "Search stories...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Saved to gallery successfully!",
            "toast_save_err" to "Error saving status.",
            "toast_deleted" to "Saved status deleted.",
            "toast_refreshed" to "Statuses refreshed",
            "tutorial_title" to "How It Works",
            "tutorial_step1" to "Go to WhatsApp and view the status you want to save.",
            "tutorial_step2" to "Watch the full status so it gets detected by the app.",
            "tutorial_step3" to "Come back and download it instantly with one tap.",
            "btn_got_it" to "Got It",
            "btn_dont_show" to "Don't Show Again",
            "rating_title" to "Your Opinion Matters To Us!",
            "rating_desc" to "Tell us how your experience was with Status Saver. Your feedback helps us grow!",
            "btn_rate_us" to "Rate Us",
            "btn_later" to "Later",
            "settings_general" to "General Settings",
            "settings_auto_save" to "Auto Save Statuses",
            "settings_notifications" to "Notifications Status",
            "settings_clear_all" to "Clear All Saved Files",
            "settings_support" to "Support & Info",
            "settings_how_to_use" to "How To Use",
            "settings_privacy" to "Privacy Policy",
            "settings_rate" to "Rate App",
            "settings_share" to "Share With Friends",
            "settings_footer_desc" to "Save and download WhatsApp statuses with ease. Never miss a moment.",
            "settings_version" to "Version 1.0.0",
            "permission_title" to "Requires Storage Folder Access",
            "permission_desc" to "Android 11+ requires granting permission to WhatsApp directory to fetch viewed statuses.",
            "permission_btn" to "Grant Folder Access",
            "storage_perm_title" to "Storage Access Required",
            "storage_perm_desc" to "On Android 10 and below, we need device storage access permission to load and save local WhatsApp status media.",
            "storage_perm_btn" to "Grant Storage Access",
            "dialog_clear_all_title" to "Clear Saved Files",
            "dialog_clear_all_desc" to "Are you sure you want to delete ALL downloaded statuses? This cannot be undone.",
            "dialog_delete" to "Delete",
            "dialog_cancel" to "Cancel",
            "empty_statuses" to "No statuses found. Open WhatsApp and view some statuses first!",
            "empty_downloads" to "You haven't saved any statuses yet. Go to Home and save some!"
        ),
        AppLanguage.HINDI to mapOf(
            "splash_title" to "डाउनलोडिंग स्टेटस सेवर 2026",
            "splash_loading" to "मीडिया इंजन तैयार किया जा रहा है...",
            "welcome_title" to "व्हाट्सएप के लिए स्टेटस सेवर",
            "welcome_desc" to "व्हाट्सएप इमेज और वीडियो तुरंत सेव करें।",
            "btn_next" to "अगला",
            "btn_skip" to "छोड़ें",
            "lang_title" to "भाषा चुनें",
            "btn_continue" to "जारी रखें",
            "onboarding_title" to "3 आसान स्टेप्स में सेव करें",
            "onboarding_step1_title" to "1. व्हाट्सएप खोलें",
            "onboarding_step1_desc" to "हमेशा की तरह व्हाट्सएप या व्हाट्सएप बिजनेस खोलें।",
            "onboarding_step2_title" to "2. स्टेटस देखें",
            "onboarding_step2_desc" to "वह पूरी इमेज या वीडियो देखें जिसे आप सेव करना चाहते हैं।",
            "onboarding_step3_title" to "3. ऐप से सेव करें",
            "onboarding_step3_desc" to "यहाँ वापस आएं और एक टैप में इसे सुरक्षित रूप से डाउनलोड करें।",
            "btn_get_started" to "शुरू करें",
            "tab_images" to "इमेज",
            "tab_videos" to "वीडियो",
            "nav_home" to "होम",
            "nav_downloads" to "डाउनलोड",
            "nav_settings" to "सेटिंग्स",
            "search_hint" to "खोजें...",
            "status_whatsapp" to "व्हाट्सएप",
            "status_whatsapp_business" to "बिजनेस",
            "toast_saved" to "गैलरी में सफलतापूर्वक सेव किया गया!",
            "toast_save_err" to "स्टेटस सेव करने में त्रुटि।",
            "toast_deleted" to "सेव किया गया स्टेटस हटा दिया गया।",
            "toast_refreshed" to "स्टेटस अपडेट कर दिए गए हैं",
            "tutorial_title" to "यह कैसे काम करता है",
            "tutorial_step1" to "व्हाट्सएप पर जाएं और उस स्टेटस को देखें जिसे आप सेव करना चाहते हैं।",
            "tutorial_step2" to "पूरा स्टेटस देखें ताकि ऐप इसे डिटेक्ट कर सके।",
            "tutorial_step3" to "शगुन के साथ तुरंत वापस आएं और एक टैप में डाउनलोड करें।",
            "btn_got_it" to "समझ गया",
            "btn_dont_show" to "दोबारा न दिखाएं",
            "rating_title" to "आपकी राय हमारे लिए महत्वपूर्ण है!",
            "rating_desc" to "हमें बताएं कि स्टेटस सेवर के साथ आपका अनुभव कैसा रहा।",
            "btn_rate_us" to "रेट करें",
            "btn_later" to "बाद में",
            "settings_general" to "सामान्य सेटिंग्स",
            "settings_auto_save" to "ऑटो सेव स्टेटस",
            "settings_notifications" to "अधिसूचना (नोटीफिकेशन)",
            "settings_clear_all" to "सभी सेव की गई फाइलें मिटाएं",
            "settings_support" to "सहायता और जानकारी",
            "settings_how_to_use" to "कैसे उपयोग करें",
            "settings_privacy" to "गोपनीयता नीति (प्राइवेसी)",
            "settings_rate" to "ऐप रेट करें",
            "settings_share" to "दोस्तों के साथ शेयर करें",
            "settings_footer_desc" to "आसानी से व्हाट्सएप स्टेटस सेव और डाउनलोड करें। कोई भी पल कभी न चूकें।",
            "settings_version" to "संस्करण 1.0.0",
            "permission_title" to "स्टोरेज फोल्डर एक्सेस आवश्यक है",
            "permission_desc" to "व्हाट्सएप स्टेटस प्राप्त करने के लिए कृपया व्हाट्सएप फोल्डर तक पहुंच की अनुमति दें।",
            "permission_btn" to "एक्सेस अनुमति दें",
            "dialog_clear_all_title" to "सभी सेव फाइलें हटाएं",
            "dialog_clear_all_desc" to "क्या आप वाकई सभी डाउनलोडेड स्टेटस हटाना चाहते हैं? इसे वापस नहीं लाया जा सकता।",
            "dialog_delete" to "हटाएं",
            "dialog_cancel" to "रद्द करें",
            "empty_statuses" to "कोई स्टेटस नहीं मिला। पहले व्हाट्सएप पर स्टेटस देखें!",
            "empty_downloads" to "आपने अभी तक कोई स्टेटस सेव नहीं किया है। होम पर जाएं और सेव करें!"
        ),
        AppLanguage.GUJARATI to mapOf(
            "splash_title" to "ડાઉનલોડિંગ સ્ટેટસ સેવર 2026",
            "splash_loading" to "મીડિયા એન્જિન તૈયાર થઈ રહ્યું છે...",
            "welcome_title" to "વોટ્સએપ સ્ટેટસ સેવર",
            "welcome_desc" to "વોટ્સએપ ફોટા અને વિડીયો તુરંત સેવ કરો.",
            "btn_next" to "આગળ",
            "btn_skip" to "જોવા ન દો",
            "lang_title" to "ભાષા પસંદ કરો",
            "btn_continue" to "ચાલુ રાખો",
            "onboarding_title" to "3 સરળ સ્ટેપ્સમાં સેવ કરો",
            "onboarding_step1_title" to "1. વોટ્સએપ ખોલો",
            "onboarding_step1_desc" to "વોટ્સએપ અથવા વોટ્સએપ બિઝનેસ ખોલો.",
            "onboarding_step2_title" to "2. સ્ટેટસ જુઓ",
            "onboarding_step2_desc" to "તમે સેવ કરવા માંગો છો તે આખો ફોટો અથવા વિડીયો જુઓ.",
            "onboarding_step3_title" to "3. આ એપ્લિકેશન દ્વારા સેવ કરો",
            "onboarding_step3_desc" to "અહીં પાછા આવો અને એક જ ક્લિકમાં તેને સેવ કરો.",
            "btn_get_started" to "શરૂ કરો",
            "tab_images" to "ફોટાઓ",
            "tab_videos" to "વિડીયોઝ",
            "nav_home" to "હોમ",
            "nav_downloads" to "ડાઉનલોડ્સ",
            "nav_settings" to "સેટિંગ્સ",
            "search_hint" to "શોધો...",
            "status_whatsapp" to "વોટ્સએપ",
            "status_whatsapp_business" to "બિઝનેસ",
            "toast_saved" to "ગેલેરીમાં સેવ થઈ ગયું છે!",
            "toast_save_err" to "સેવ કરવામાં ભૂલ આવી.",
            "toast_deleted" to "સેવ કરેલું સ્ટેટસ કાઢી નાખવામાં આવ્યું.",
            "toast_refreshed" to "સ્ટેટસ અપડેટ થઈ ગયા છે",
            "tutorial_title" to "કઈ રીતે કામ કરે છે?",
            "tutorial_step1" to "વોટ્સએપમાં જાઓ અને જે સ્ટેટસ સેવ કરવું હોય તે જુઓ.",
            "tutorial_step2" to "સ્ટેટસ આખું જુઓ જેથી એપ તેને શોધી શકે.",
            "tutorial_step3" to "પાછા આવીને એક જ ટૅપમાં તેને ડાઉનલોડ કરો.",
            "btn_got_it" to "સમજાઈ ગયું",
            "btn_dont_show" to "ફરીથી ન બતાવો",
            "rating_title" to "તમારો અભિપ્રાય અમારા માટે મહત્વપૂર્ણ છે!",
            "rating_desc" to "અમને જણાવો કે આ એપ સાથે તમારો અનુભવ કેવો રહ્યો.",
            "btn_rate_us" to "રેટિંગ આપો",
            "btn_later" to "પછીથી",
            "settings_general" to "સામાન્ય સેટિંગ્સ",
            "settings_auto_save" to "ઓટો સેવ સ્ટેટસ",
            "settings_notifications" to "નોટિફિકેશન સૂચના",
            "settings_clear_all" to "બધી સેવ કરેલી ફાઈલો કાઢી નાખો",
            "settings_support" to "સપોર્ટ અને માહિતી",
            "settings_how_to_use" to "કઈ રીતે વાપરવું",
            "settings_privacy" to "પ્રાઇવસી પોલીસી",
            "settings_rate" to "એપ રેટ કરો",
            "settings_share" to "મિત્રો સાથે શેર કરો",
            "settings_footer_desc" to "સરળતાથી વોટ્સએપ સ્ટેટસ ડાઉનલોડ અને સેવ કરો. કોઈ પણ પળ ચૂકશો નહીં.",
            "settings_version" to "વર્ઝન 1.0.0",
            "permission_title" to "સ્ટોરેજ ફોલ્ડર મંજૂરી જરૂરી છે",
            "permission_desc" to "વોટ્સએપ સ્ટેટસ જોવા માટે કૃપા કરીને વોટ્સએપ ડિરેક્ટરીની પરવાનગી આપો.",
            "permission_btn" to "ફોલ્ડર મંજૂરી આપો",
            "dialog_clear_all_title" to "ફાઈલો કાઢી નાખો",
            "dialog_clear_all_desc" to "શું તમે ખરેખર બધી ફાઈલો કાઢી નાખવા માંગો છો? આ પાછું નહિ મળી શકે.",
            "dialog_delete" to "નિકાલ કરો",
            "dialog_cancel" to "રદ કરો",
            "empty_statuses" to "કોઈ સ્ટેટસ મળ્યા નથી. વોટ્સએપ પર પેલા સ્ટેટસ જુઓ!",
            "empty_downloads" to "તમે હજુ સુધી કોઈ સ્ટેટસ સેવ કર્યું નથી. હોમ માં જઈને સેવ કરો!"
        ),
        AppLanguage.MARATHI to mapOf(
            "splash_title" to "डाऊनलोडिंग स्टेटस सेव्हर 2026",
            "splash_loading" to "मीडिया इंजिन तयार होत आहे...",
            "welcome_title" to "स्टेटस सेव्हर",
            "welcome_desc" to "व्हॉट्सॲपचे फोटो आणि व्हिडिओ झटपट सेव्ह करा.",
            "btn_next" to "पुढील",
            "btn_skip" to "वगळा",
            "lang_title" to "भाषा निवडा",
            "btn_continue" to "सुरू ठेवा",
            "onboarding_title" to "३ सोप्या स्टेप्समध्ये सेव्ह करा",
            "onboarding_step1_title" to "1. व्हॉट्सॲप उघडा",
            "onboarding_step1_desc" to "व्हॉट्सॲप किंवा व्हॉट्सॲप बिझनेस नेहमीसारखे उघडा.",
            "onboarding_step2_title" to "2. स्टेटस पहा",
            "onboarding_step2_desc" to "तुम्हाला सेव्ह करायचा असलेला संपूर्ण फोटो किंवा व्हिडिओ पहा.",
            "onboarding_step3_title" to "3. या ॲपवरून सेव्ह करा",
            "onboarding_step3_desc" to "इथे परत या आणि एका क्लिकवर सुरक्षितपणे डाउनलोड करा.",
            "btn_get_started" to "सुरू करा",
            "tab_images" to "फोटो",
            "tab_videos" to "व्हिडिओ",
            "nav_home" to "होम",
            "nav_downloads" to "डाउनलोड्स",
            "nav_settings" to "सेटिंग्ज",
            "search_hint" to "शोध...",
            "status_whatsapp" to "व्हॉट्सॲप",
            "status_whatsapp_business" to "बिझनेस",
            "toast_saved" to "गॅलरीमध्ये यशस्वीरित्या सेव्ह झाले!",
            "toast_save_err" to "सेव्ह करताना एरर आली.",
            "toast_deleted" to "सेव्ह केलेले स्टेटस हटवले गेले.",
            "toast_refreshed" to "स्टेटस अपडेट झाले आहेत",
            "tutorial_title" to "हे कसे काम करते?",
            "tutorial_step1" to "व्हॉट्सॲपवर जा आणि तुम्हाला हवे असलेले स्टेटस पहा.",
            "tutorial_step2" to "संपूर्ण स्टेटस नक्की पहा जेणेकरून ॲप ते शोधू शकेल.",
            "tutorial_step3" to "परत या आणि एका क्लिकमध्ये डाउनलोड करा.",
            "btn_got_it" to "समजले",
            "btn_dont_show" to "पुन्हा दाखवू नका",
            "rating_title" to "तुमचे मत आमच्यासाठी महत्त्वाचे आहे!",
            "rating_desc" to "अ‍ॅपबद्दल तुमचा अनुभव कसा होता ते सांगा.",
            "btn_rate_us" to "रेट करा",
            "btn_later" to "नंतर",
            "settings_general" to "सामान्य सेटिंग्ज",
            "settings_auto_save" to "ऑटो सेव्ह स्टेटस",
            "settings_notifications" to "सूचना स्थिती",
            "settings_clear_all" to "सर्व सेव्ह केलेल्या फाईल्स हटवा",
            "settings_support" to "मदत आणि माहिती",
            "settings_how_to_use" to "कसे वापरावे",
            "settings_privacy" to "गोपनीयता धोरण (प्रायव्हसी)",
            "settings_rate" to "ॲप रेट करा",
            "settings_share" to "मित्रांसोबत शेअर करा",
            "settings_footer_desc" to "सहजपणे व्हॉट्सॲप स्टेटस डाउनलोड आणि सेव्ह करा. कोणताही क्षण चुकवू नका.",
            "settings_version" to "व्हर्जन 1.0.0",
            "permission_title" to "स्टोरेज फोल्डर परवानगी आवश्यक",
            "permission_desc" to "व्हॉट्सॲप स्टेटस पाहण्यासाठी व्हॉट्सॲप फोल्डरच्या प्रवेशास परवानगी द्या.",
            "permission_btn" to "परवानगी द्या",
            "dialog_clear_all_title" to "फायली हटवा",
            "dialog_clear_all_desc" to "तुम्ही नक्की सर्व फायली हटवू इच्छिता? हे परत मिळवता येणार नाही.",
            "dialog_delete" to "हटवा",
            "dialog_cancel" to "रद्द करा",
            "empty_statuses" to "कोणतेही स्टेटस सापडले नाही. व्हॉट्सॲपवर स्टेटस पहा!",
            "empty_downloads" to "तुम्ही अद्याप कोणतेही स्टेटस सेव्ह केलेले नाही. होम वरून सेव्ह करा!"
        ),
        AppLanguage.TAMIL to mapOf(
            "splash_title" to "பதிவிறக்கம் செய்யப்படுகிறது ஸ்டேட்டஸ் சேவர்",
            "splash_loading" to "மீடியா எஞ்சின் தயாராகிறது...",
            "welcome_title" to "வாட்ஸ்அப் ஸ்டேட்டஸ் சேவர்",
            "welcome_desc" to "வாட்ஸ்அப் படங்கள் மற்றும் வீடியோக்களை உடனடியாக சேமிக்கவும்.",
            "btn_next" to "அடுத்து",
            "btn_skip" to "தவிர்",
            "lang_title" to "மொழியைத் தேர்ந்தெடுக்கவும்",
            "btn_continue" to "தொடரவும்",
            "onboarding_title" to "3 எளிய வழிகளில் சேமிக்கவும்",
            "onboarding_step1_title" to "1. வாட்ஸ்அப்பைத் திறக்கவும்",
            "onboarding_step1_desc" to "வழக்கம் போல் உங்கள் வாட்ஸ்அப் செயலியைத் திறக்கவும்.",
            "onboarding_step2_title" to "2. ஸ்டேட்டஸைப் பார்க்கவும்",
            "onboarding_step2_desc" to "நீங்கள் சேமிக்க விரும்பும் முழு படத்தையோ அல்லது வீடியோவையோ பார்க்கவும்.",
            "onboarding_step3_title" to "3. இந்த செயலி மூலம் சேமிக்கவும்",
            "onboarding_step3_desc" to "இங்கு திரும்பி வந்து ஒரே டப்பில் பாதுகாப்பாக பதிவிறக்கவும்.",
            "btn_get_started" to "தொடங்குங்கள்",
            "tab_images" to "படங்கள்",
            "tab_videos" to "வீடியோக்கள்",
            "nav_home" to "முகப்பு",
            "nav_downloads" to "பதிவிறக்கங்கள்",
            "nav_settings" to "அமைப்புகள்",
            "search_hint" to "தேடுக...",
            "status_whatsapp" to "வாட்ஸ்அப்",
            "status_whatsapp_business" to "பிசினஸ்",
            "toast_saved" to "கேலரியில் வெற்றிகரமாக சேமிக்கப்பட்டது!",
            "toast_save_err" to "சேமிப்பதில் பிழை ஏற்பட்டது.",
            "toast_deleted" to "சேமிக்கப்பட்ட கோப்பு நீக்கப்பட்டது.",
            "toast_refreshed" to "ஸ்டேட்டஸ்கள் புதுப்பிக்கப்பட்டன",
            "tutorial_title" to "இது எப்படி வேலை செய்கிறது?",
            "tutorial_step1" to "வாட்ஸ்அப் சென்று நீங்கள் சேமிக்க விரும்பும் ஸ்டேட்டஸைப் பாருங்கள்.",
            "tutorial_step2" to "எங்கள் செயலி கண்டறிய, ஸ்டேட்டஸை முழுமையாகப் பாருங்கள்.",
            "tutorial_step3" to "இங்கு வந்து உடனடியாக ஒரே தட்டில் பதிவிறக்குங்கள்.",
            "btn_got_it" to "புரிந்தது",
            "btn_dont_show" to "மீண்டும் காட்டாதே",
            "rating_title" to "உங்கள் கருத்து எங்களுக்கு முக்கியம்!",
            "rating_desc" to "எங்கள் செயலியின் அனுபவத்தை எங்களுடன் பகிர்ந்து கொள்ளுங்கள்.",
            "btn_rate_us" to "மதிப்பிடவும்",
            "btn_later" to "பிறகு",
            "settings_general" to "பொதுவான அமைப்புகள்",
            "settings_auto_save" to "தானியங்கி சேமிப்பு (ஆட்டோ)",
            "settings_notifications" to "அறிவிப்புகளின் நிலை",
            "settings_clear_all" to "சேமித்த கோப்புகளை நீக்கு",
            "settings_support" to "ஆதரவு மற்றும் தகவல்",
            "settings_how_to_use" to "பயன்படுத்துவது எப்படி",
            "settings_privacy" to "தனியுரிமை கொள்கை",
            "settings_rate" to "செயலியை மதிப்பிடு",
            "settings_share" to "நண்பர்களுடன் பகிர்க",
            "settings_footer_desc" to "சுலபமாக வாட்ஸ்அப் ஸ்டேட்டஸ்களைப் பதிவிறக்கி சேமிக்கவும். எதையும் தவறவிடாதீர்கள்.",
            "settings_version" to "பதிப்பு 1.0.0",
            "permission_title" to "அனுமதி தேவைப்படுகிறது",
            "permission_desc" to "வாட்ஸ்அப் கோப்பகத்தை அணுக அனுமதி அளித்தால் மட்டுமே ஸ்டேட்டஸ்களைக் காட்ட முடியும்.",
            "permission_btn" to "அனுமதி அளிக்கவும்",
            "dialog_clear_all_title" to "கோப்புகளை நீக்குக",
            "dialog_clear_all_desc" to "சேமித்த அனைத்து கோப்புகளையும் நீக்க வேண்டுமா? இதை மாற்ற முடியாது.",
            "dialog_delete" to "நீக்குக",
            "dialog_cancel" to "ரத்து செய்",
            "empty_statuses" to "ஸ்டேட்டஸ் எதுவும் கிடைக்கவில்லை. முதலில் வாட்ஸ்அப்பில் பார்க்கவும்!",
            "empty_downloads" to "சேமிக்கப்பட்ட ஸ்டேட்டஸ்கள் எதுவும் இல்லை. முகப்புச் சென்று சேமிக்கவும்!"
        ),
        AppLanguage.SPANISH to mapOf(
            "splash_title" to "Descargador de Estados 2026",
            "splash_loading" to "Preparando motor de medios...",
            "welcome_title" to "Ahorrador de Estados para WhatsApp",
            "welcome_desc" to "Guarda fotos y videos de WhatsApp al instante.",
            "btn_next" to "Siguiente",
            "btn_skip" to "Omitir",
            "lang_title" to "Seleccionar idioma",
            "btn_continue" to "Continuar",
            "onboarding_title" to "Guarda en 3 simples pasos",
            "onboarding_step1_title" to "1. Abre WhatsApp",
            "onboarding_step1_desc" to "Abre WhatsApp o WhatsApp Business normalmente.",
            "onboarding_step2_title" to "2. Mira el estado",
            "onboarding_step2_desc" to "Mira la foto o video completo que deseas guardar.",
            "onboarding_step3_title" to "3. Guarda desde la aplicación",
            "onboarding_step3_desc" to "Regresa aquí y descárgalo de forma segura con un toque.",
            "btn_get_started" to "Empezar",
            "tab_images" to "Imágenes",
            "tab_videos" to "Videos",
            "nav_home" to "Inicio",
            "nav_downloads" to "Descargas",
            "nav_settings" to "Ajustes",
            "search_hint" to "Buscar estados...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "¡Guardado en la galería con éxito!",
            "toast_save_err" to "Error al guardar el estado.",
            "toast_deleted" to "Estado guardado eliminado.",
            "toast_refreshed" to "Estados actualizados",
            "tutorial_title" to "Cómo funciona",
            "tutorial_step1" to "Ve a WhatsApp y mira el estado que deseas guardar.",
            "tutorial_step2" to "Mira el estado completo para que la aplicación lo detecte.",
            "tutorial_step3" to "Regresa y descárgalo al instante con un toque.",
            "btn_got_it" to "Entendido",
            "btn_dont_show" to "No volver a mostrar",
            "rating_title" to "¡Tu opinión nos importa!",
            "rating_desc" to "Cuéntanos tu experiencia con el Ahorrador de Estados.",
            "btn_rate_us" to "Calificar",
            "btn_later" to "Más tarde",
            "settings_general" to "Ajustes generales",
            "settings_auto_save" to "Guardar automáticamente",
            "settings_notifications" to "Notificaciones de estado",
            "settings_clear_all" to "Borrar todos los archivos",
            "settings_support" to "Soporte e información",
            "settings_how_to_use" to "Cómo usar",
            "settings_privacy" to "Política de privacidad",
            "settings_rate" to "Calificar aplicación",
            "settings_share" to "Compartir con amigos",
            "settings_footer_desc" to "Guarda y descarga estados de WhatsApp fácilmente. No te pierdas ningún momento.",
            "settings_version" to "Versión 1.0.0",
            "permission_title" to "Requiere acceso a la carpeta",
            "permission_desc" to "Android 11+ requiere otorgar permiso a la carpeta de WhatsApp para obtener los estados.",
            "permission_btn" to "Otorgar acceso",
            "dialog_clear_all_title" to "Borrar archivos guardados",
            "dialog_clear_all_desc" to "¿Estás seguro de que deseas eliminar TODOS los estados descargados? Esto no se puede deshacer.",
            "dialog_delete" to "Eliminar",
            "dialog_cancel" to "Cancelar",
            "empty_statuses" to "No se encontraron estados. ¡Abre WhatsApp y mira algunos estados primero!",
            "empty_downloads" to "Aún no has guardado ningún estado. ¡Ve a Inicio y guarda algunos!"
        ),
        AppLanguage.FRENCH to mapOf(
            "splash_title" to "Téléchargeur de Statut 2026",
            "splash_loading" to "Préparation du moteur multimédia...",
            "welcome_title" to "Économiseur de Statut pour WhatsApp",
            "welcome_desc" to "Enregistrez instantanément les photos et vidéos WhatsApp.",
            "btn_next" to "Suivant",
            "btn_skip" to "Passer",
            "lang_title" to "Choisir la langue",
            "btn_continue" to "Continuer",
            "onboarding_title" to "Enregistrez en 3 étapes simples",
            "onboarding_step1_title" to "1. Ouvrez WhatsApp",
            "onboarding_step1_desc" to "Ouvrez WhatsApp ou WhatsApp Business comme d'habitude.",
            "onboarding_step2_title" to "2. Regardez le statut",
            "onboarding_step2_desc" to "Examinez l'image ou la vidéo entière que vous souhaitez enregistrer.",
            "onboarding_step3_title" to "3. Enregistrez depuis l'application",
            "onboarding_step3_desc" to "Revenez ici et téléchargez-le en toute sécurité en un seul clic.",
            "btn_get_started" to "Commencer",
            "tab_images" to "Images",
            "tab_videos" to "Vidéos",
            "nav_home" to "Accueil",
            "nav_downloads" to "Téléchargements",
            "nav_settings" to "Paramètres",
            "search_hint" to "Rechercher des statuts...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Enregistré dans la galerie avec succès !",
            "toast_save_err" to "Erreur lors de l'enregistrement du statut.",
            "toast_deleted" to "Statut enregistré supprimé.",
            "toast_refreshed" to "Statuts actualisés",
            "tutorial_title" to "Comment ça marche",
            "tutorial_step1" to "Allez sur WhatsApp et regardez le statut que vous souhaitez enregistrer.",
            "tutorial_step2" to "Regardez le statut en entier pour que l'application puisse le détecter.",
            "tutorial_step3" to "Revenez et téléchargez-le instantanément en un clic.",
            "btn_got_it" to "Compris",
            "btn_dont_show" to "Ne plus afficher",
            "rating_title" to "Votre avis compte pour nous !",
            "rating_desc" to "Dites-nous ce que vous pensez de l'Économiseur de Statut.",
            "btn_rate_us" to "Évaluer",
            "btn_later" to "Plus tard",
            "settings_general" to "Paramètres généraux",
            "settings_auto_save" to "Enregistrement automatique",
            "settings_notifications" to "Notifications de statut",
            "settings_clear_all" to "Effacer tous les fichiers",
            "settings_support" to "Assistance et infos",
            "settings_how_to_use" to "Comment utiliser",
            "settings_privacy" to "Politique de confidentialité",
            "settings_rate" to "Évaluer l'application",
            "settings_share" to "Partager avec des amis",
            "settings_footer_desc" to "Enregistrez et téléchargez facilement les statuts WhatsApp. Ne manquez aucun moment.",
            "settings_version" to "Version 1.0.0",
            "permission_title" to "Accès au dossier requis",
            "permission_desc" to "Android 11+ nécessite l'autorisation d'accéder au dossier WhatsApp pour récupérer les statuts.",
            "permission_btn" to "Autoriser l'accès",
            "dialog_clear_all_title" to "Effacer les fichiers enregistrés",
            "dialog_clear_all_desc" to "Êtes-vous sûr de vouloir supprimer TOUS les statuts téléchargés ? Cette action est irréversible.",
            "dialog_delete" to "Supprimer",
            "dialog_cancel" to "Annuler",
            "empty_statuses" to "Aucun statut trouvé. Ouvrez WhatsApp et regardez d'abord des statuts !",
            "empty_downloads" to "Vous n'avez encore enregistré aucun statut. Allez à l'accueil et enregistrez-en !"
        ),
        AppLanguage.PORTUGUESE to mapOf(
            "splash_title" to "Baixador de Status 2026",
            "splash_loading" to "Preparando motor de mídia...",
            "welcome_title" to "Economizador de Status para WhatsApp",
            "welcome_desc" to "Salve fotos e vídeos do WhatsApp instantaneamente.",
            "btn_next" to "Avançar",
            "btn_skip" to "Pular",
            "lang_title" to "Selecionar Idioma",
            "btn_continue" to "Continuar",
            "onboarding_title" to "Salve em 3 passos simples",
            "onboarding_step1_title" to "1. Abra o WhatsApp",
            "onboarding_step1_desc" to "Abra o WhatsApp ou WhatsApp Business normalmente.",
            "onboarding_step2_title" to "2. Veja o Status",
            "onboarding_step2_desc" to "Veja a foto ou vídeo completo que você deseja salvar.",
            "onboarding_step3_title" to "3. Salve pelo aplicativo",
            "onboarding_step3_desc" to "Volte aqui e baixe com segurança com apenas um toque.",
            "btn_get_started" to "Começar",
            "tab_images" to "Imagens",
            "tab_videos" to "Vídeos",
            "nav_home" to "Início",
            "nav_downloads" to "Downloads",
            "nav_settings" to "Configurações",
            "search_hint" to "Pesquisar status...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Salvo na galeria com sucesso!",
            "toast_save_err" to "Erro ao salvar status.",
            "toast_deleted" to "Status salvo excluído.",
            "toast_refreshed" to "Status atualizados",
            "tutorial_title" to "Como funciona",
            "tutorial_step1" to "Vá para o WhatsApp e veja o status que você deseja salvar.",
            "tutorial_step2" to "Assista ao status completo para que o aplicativo possa detectá-lo.",
            "tutorial_step3" to "Volte e baixe instantaneamente com um toque.",
            "btn_got_it" to "Entendido",
            "btn_dont_show" to "Não mostrar novamente",
            "rating_title" to "Sua opinião é importante!",
            "rating_desc" to "Conte-nos como foi sua experiência com o Economizador de Status.",
            "btn_rate_us" to "Avaliar",
            "btn_later" to "Mais tarde",
            "settings_general" to "Configurações Gerais",
            "settings_auto_save" to "Salvar Automaticamente",
            "settings_notifications" to "Notificações de Status",
            "settings_clear_all" to "Apagar Arquivos Salvos",
            "settings_support" to "Suporte e Informações",
            "settings_how_to_use" to "Como Usar",
            "settings_privacy" to "Política de Privacidade",
            "settings_rate" to "Avaliar Aplicativo",
            "settings_share" to "Compartilhar com Amigos",
            "settings_footer_desc" to "Salve e baixe status do WhatsApp facilmente. Nunca perca um momento.",
            "settings_version" to "Versão 1.0.0",
            "permission_title" to "Acesso à Pasta Requerido",
            "permission_desc" to "O Android 11+ exige que você conceda permissão para a pasta do WhatsApp para buscar os status vistos.",
            "permission_btn" to "Conceder Acesso",
            "dialog_clear_all_title" to "Apagar Arquivos Salvos",
            "dialog_clear_all_desc" to "Tem certeza de que deseja excluir TODOS os status baixados? Isso não pode ser desfeito.",
            "dialog_delete" to "Excluir",
            "dialog_cancel" to "Cancelar",
            "empty_statuses" to "Nenhum status encontrado. Abra o WhatsApp e veja alguns status primeiro!",
            "empty_downloads" to "Você ainda não salvou nenhum status. Vá para o Início e salve alguns!"
        ),
        AppLanguage.GERMAN to mapOf(
            "splash_title" to "Status-Downloader 2026",
            "splash_loading" to "Medien-Engine wird vorbereitet...",
            "welcome_title" to "Status-Saver für WhatsApp",
            "welcome_desc" to "WhatsApp-Bilder und -Videos sofort speichern.",
            "btn_next" to "Weiter",
            "btn_skip" to "Überspringen",
            "lang_title" to "Sprache auswählen",
            "btn_continue" to "Weiter",
            "onboarding_title" to "In 3 einfachen Schritten speichern",
            "onboarding_step1_title" to "1. WhatsApp öffnen",
            "onboarding_step1_desc" to "Öffnen Sie WhatsApp oder WhatsApp Business wie gewohnt.",
            "onboarding_step2_title" to "2. Status ansehen",
            "onboarding_step2_desc" to "Sehen Sie sich das gesamte Bild oder Video an, das Sie speichern möchten.",
            "onboarding_step3_title" to "3. Über die App speichern",
            "onboarding_step3_desc" to "Kommen Sie hierher zurück und laden Sie es sicher mit einem Fingertipp herunter.",
            "btn_get_started" to "Loslegen",
            "tab_images" to "Bilder",
            "tab_videos" to "Videos",
            "nav_home" to "Startseite",
            "nav_downloads" to "Downloads",
            "nav_settings" to "Einstellungen",
            "search_hint" to "Status suchen...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Erfolgreich in der Galerie gespeichert!",
            "toast_save_err" to "Fehler beim Speichern des Status.",
            "toast_deleted" to "Gespeicherter Status gelöscht.",
            "toast_refreshed" to "Status aktualisiert",
            "tutorial_title" to "So funktioniert es",
            "tutorial_step1" to "Gehen Sie zu WhatsApp und sehen Sie sich den Status an, den Sie speichern möchten.",
            "tutorial_step2" to "Sehen Sie sich den gesamten Status an, damit die App ihn erkennen kann.",
            "tutorial_step3" to "Kommen Sie zurück und laden ihn sofort mit einem Fingertipp herunter.",
            "btn_got_it" to "Verstanden",
            "btn_dont_show" to "Nicht mehr anzeigen",
            "rating_title" to "Ihre Meinung ist uns wichtig!",
            "rating_desc" to "Teilen Sie uns Ihre Erfahrungen mit dem Status Saver mit.",
            "btn_rate_us" to "Bewerten",
            "btn_later" to "Später",
            "settings_general" to "Allgemeine Einstellungen",
            "settings_auto_save" to "Status automatisch speichern",
            "settings_notifications" to "Benachrichtigungsstatus",
            "settings_clear_all" to "Alle gespeicherten Dateien löschen",
            "settings_support" to "Support & Infos",
            "settings_how_to_use" to "Bedienung",
            "settings_privacy" to "Datenschutzrichtlinie",
            "settings_rate" to "App bewerten",
            "settings_share" to "Mit Freunden teilen",
            "settings_footer_desc" to "WhatsApp-Status einfach speichern und herunterladen. Verpassen Sie keinen Moment.",
            "settings_version" to "Version 1.0.0",
            "permission_title" to "Zugriff auf Speicherordner erforderlich",
            "permission_desc" to "Android 11+ erfordert die Freigabe des WhatsApp-Ordners, um angesehene Status abzurufen.",
            "permission_btn" to "Zugriff gewähren",
            "dialog_clear_all_title" to "Gespeicherte Dateien löschen",
            "dialog_clear_all_desc" to "Sind Sie sicher, dass Sie ALLE heruntergeladenen Status löschen möchten? Dies kann nicht rückgängig gemacht werden.",
            "dialog_delete" to "Löschen",
            "dialog_cancel" to "Abbrechen",
            "empty_statuses" to "Keine Status gefunden. Öffnen Sie WhatsApp und sehen Sie sich zuerst Status an!",
            "empty_downloads" to "Sie haben noch keine Status gespeichert. Gehen Sie auf Startseite und speichern Sie welche!"
        ),
        AppLanguage.ARABIC to mapOf(
            "splash_title" to "حافظ حالات واتساب 2026",
            "splash_loading" to "جاري تهيئة محرك الوسائط...",
            "welcome_title" to "حفظ حالات واتساب",
            "welcome_desc" to "احفظ صور وفيديوهات واتساب على الفور.",
            "btn_next" to "التالي",
            "btn_skip" to "تخطي",
            "lang_title" to "اختر اللغة",
            "btn_continue" to "متابعة",
            "onboarding_title" to "احفظ في 3 خطوات بسيطة",
            "onboarding_step1_title" to "1. افتح واتساب",
            "onboarding_step1_desc" to "افتح تطبيق واتساب أو واتساب للأعمال كالمعتاد.",
            "onboarding_step2_title" to "2. شاهد الحالة",
            "onboarding_step2_desc" to "شاهد الصورة أو الفيديو الكامل الذي تريد حفظه.",
            "onboarding_step3_title" to "3. احفظ من التطبيق",
            "onboarding_step3_desc" to "ارجع إلى هنا وقم بتنزيلها بأمان بنقرة واحدة.",
            "btn_get_started" to "ابدأ الآن",
            "tab_images" to "الصور",
            "tab_videos" to "الفيديوهات",
            "nav_home" to "الرئيسية",
            "nav_downloads" to "التنزيلات",
            "nav_settings" to "الإعدادات",
            "search_hint" to "البحث عن الحالات...",
            "status_whatsapp" to "واتساب عادي",
            "status_whatsapp_business" to "واتساب أعمال",
            "toast_saved" to "تم الحفظ في المعرض بنجاح!",
            "toast_save_err" to "حدث خطأ أثناء حفظ الحالة.",
            "toast_deleted" to "تم حذف الحالة المحفوظة.",
            "toast_refreshed" to "تم تحديث الحالات",
            "tutorial_title" to "كيف يعمل التطبيق",
            "tutorial_step1" to "اذهب إلى واتساب وشاهد الحالة التي تريد حفظها.",
            "tutorial_step2" to "شاهد الحالة كاملة حتى يتمكن التطبيق من اكتشافها.",
            "tutorial_step3" to "ارجع وحملها على الفور بنقرة واحدة.",
            "btn_got_it" to "فهمت",
            "btn_dont_show" to "لا تبينها مرة أخرى",
            "rating_title" to "رأيك يهمنا!",
            "rating_desc" to "أخبرنا برأيك وتجربتك مع حافظ الحالات.",
            "btn_rate_us" to "تقييم التطبيق",
            "btn_later" to "لاحقاً",
            "settings_general" to "الإعدادات العامة",
            "settings_auto_save" to "الحفظ التلقائي للحالات",
            "settings_notifications" to "حالة الإشعارات",
            "settings_clear_all" to "حذف جميع الملفات المحفوظة",
            "settings_support" to "الدعم والمعلومات",
            "settings_how_to_use" to "كيفية الاستخدام",
            "settings_privacy" to "سياسة الخصوصية",
            "settings_rate" to "تقييم التطبيق",
            "settings_share" to "مشاركة مع الأصدقاء",
            "settings_footer_desc" to "احفظ وحمل حالات واتساب بسهولة. لا تفوت أي لحظة أبداً.",
            "settings_version" to "الإصدار 1.0.0",
            "permission_title" to "مطلوب الإذن للوصول للمجلد",
            "permission_desc" to "يتطلب نظام أندرويد 11 فما فوق منح الإذن للوصول لمجلد واتساب لجلب الحالات المشاهدة.",
            "permission_btn" to "منح الإذن",
            "dialog_clear_all_title" to "حذف الملفات المحفوظة",
            "dialog_clear_all_desc" to "هل أنت متأكد من رغبتك في حذف جميع الحالات المحملة؟ لا يمكن التراجع عن هذا الإجراء.",
            "dialog_delete" to "حذف",
            "dialog_cancel" to "إلغاء",
            "empty_statuses" to "لم يتم العثور على حالات. افتح واتساب وشاهد بعض الحالات أولاً!",
            "empty_downloads" to "لم تقم بحفظ أي حالات بعد. اذهب للرئيسية واحفظ البعض!"
        ),
        AppLanguage.INDONESIAN to mapOf(
            "splash_title" to "Pengunduh Status 2026",
            "splash_loading" to "Menyiapkan Mesin Media...",
            "welcome_title" to "Penghemat Status WhatsApp",
            "welcome_desc" to "Simpan gambar dan video WhatsApp secara instan.",
            "btn_next" to "Berikutnya",
            "btn_skip" to "Lewati",
            "lang_title" to "Pilih Bahasa",
            "btn_continue" to "Lanjutkan",
            "onboarding_title" to "Simpan dalam 3 Langkah Mudah",
            "onboarding_step1_title" to "1. Buka WhatsApp",
            "onboarding_step1_desc" to "Buka WhatsApp atau WhatsApp Business seperti biasa.",
            "onboarding_step2_title" to "2. Lihat Status",
            "onboarding_step2_desc" to "Tonton gambar atau video lengkap yang ingin Anda simpan.",
            "onboarding_step3_title" to "3. Simpan dari Aplikasi",
            "onboarding_step3_desc" to "Kembali ke sini dan unduh dengan aman dengan satu ketukan.",
            "btn_get_started" to "Mulai",
            "tab_images" to "Gambar",
            "tab_videos" to "Video",
            "nav_home" to "Beranda",
            "nav_downloads" to "Unduhan",
            "nav_settings" to "Pengaturan",
            "search_hint" to "Cari cerita...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Berhasil disimpan ke galeri!",
            "toast_save_err" to "Gagal menyimpan status.",
            "toast_deleted" to "Status tersimpan dihapus.",
            "toast_refreshed" to "Status diperbarui",
            "tutorial_title" to "Cara Kerja",
            "tutorial_step1" to "Buka WhatsApp dan lihat status yang ingin Anda simpan.",
            "tutorial_step2" to "Tonton status secara lengkap agar dapat terdeteksi oleh aplikasi.",
            "tutorial_step3" to "Kembali dan unduh secara instan dengan satu ketukan.",
            "btn_got_it" to "Mengerti",
            "btn_dont_show" to "Jangan Tampilkan Lagi",
            "rating_title" to "Pendapat Anda Penting!",
            "rating_desc" to "Beri tahu kami bagaimana pengalaman Anda menggunakan Penghemat Status.",
            "btn_rate_us" to "Beri Nilai",
            "btn_later" to "Nanti",
            "settings_general" to "Pengaturan Umum",
            "settings_auto_save" to "Simpan Otomatis Status",
            "settings_notifications" to "Status Notifikasi",
            "settings_clear_all" to "Hapus Semua File Tersimpan",
            "settings_support" to "Dukungan & Info",
            "settings_how_to_use" to "Cara Penggunaan",
            "settings_privacy" to "Kebijakan Privasi",
            "settings_rate" to "Beri Nilai Aplikasi",
            "settings_share" to "Bagikan dengan Teman",
            "settings_footer_desc" to "Simpan dan unduh status WhatsApp dengan mudah. Jangan lewatkan setiap momen.",
            "settings_version" to "Versi 1.0.0",
            "permission_title" to "Memerlukan Akses Folder Penyimpanan",
            "permission_desc" to "Android 11+ memerlukan pemberian izin ke folder WhatsApp untuk mengambil status yang dilihat.",
            "permission_btn" to "Berikan Akses Folder",
            "dialog_clear_all_title" to "Hapus File Tersimpan",
            "dialog_clear_all_desc" to "Apakah Anda yakin ingin menghapus SEMUA status yang diunduh? Tindakan ini tidak dapat dibatalkan.",
            "dialog_delete" to "Hapus",
            "dialog_cancel" to "Batal",
            "empty_statuses" to "Tidak ada status ditemukan. Buka WhatsApp dan lihat beberapa status terlebih dahulu!",
            "empty_downloads" to "Anda belum menyimpan status apa pun. Pergi ke Beranda dan simpan beberapa!"
        ),
        AppLanguage.RUSSIAN to mapOf(
            "splash_title" to "Загрузчик статусов 2026",
            "splash_loading" to "Подготовка медиа-движка...",
            "welcome_title" to "Сохранение статуса для WhatsApp",
            "welcome_desc" to "Мгновенно сохраняйте фото и видео из WhatsApp.",
            "btn_next" to "Далее",
            "btn_skip" to "Пропустить",
            "lang_title" to "Выберите язык",
            "btn_continue" to "Продолжить",
            "onboarding_title" to "Сохраняйте за 3 простых шага",
            "onboarding_step1_title" to "1. Откройте WhatsApp",
            "onboarding_step1_desc" to "Откройте WhatsApp или WhatsApp Business как обычно.",
            "onboarding_step2_title" to "2. Посмотрите статус",
            "onboarding_step2_desc" to "Просмотрите нужное фото или видео полностью.",
            "onboarding_step3_title" to "3. Сохраните в приложении",
            "onboarding_step3_desc" to "Вернитесь сюда и безопасно скачайте одним нажатием.",
            "btn_get_started" to "Начать",
            "tab_images" to "Фото",
            "tab_videos" to "Видео",
            "nav_home" to "Главная",
            "nav_downloads" to "Загрузки",
            "nav_settings" to "Настройки",
            "search_hint" to "Поиск статусов...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Успешно сохранено в галерею!",
            "toast_save_err" to "Ошибка при сохранении.",
            "toast_deleted" to "Сохраненный статус удален.",
            "toast_refreshed" to "Статусы обновлены",
            "tutorial_title" to "Как это работает",
            "tutorial_step1" to "Откройте WhatsApp и просмотрите статус, который вы хотите сохранить.",
            "tutorial_step2" to "Посмотрите статус целиком, чтобы приложение его обнаружило.",
            "tutorial_step3" to "Вернитесь и мгновенно скачайте его одним нажатием.",
            "btn_got_it" to "Понятно",
            "btn_dont_show" to "Не показывать снова",
            "rating_title" to "Нам важно ваше мнение!",
            "rating_desc" to "Расскажите нам о вашем опыте работы с приложением.",
            "btn_rate_us" to "Оценить нас",
            "btn_later" to "Позже",
            "settings_general" to "Общие настройки",
            "settings_auto_save" to "Автосохранение статусов",
            "settings_notifications" to "Уведомления о статусах",
            "settings_clear_all" to "Очистить все файлы",
            "settings_support" to "Поддержка и инфо",
            "settings_how_to_use" to "Руководство",
            "settings_privacy" to "Политика конфиденциальности",
            "settings_rate" to "Оценить приложение",
            "settings_share" to "Поделиться с друзьями",
            "settings_footer_desc" to "Легко сохраняйте и скачивайте статусы WhatsApp. Не упустите ни одного момента.",
            "settings_version" to "Версия 1.0.0",
            "permission_title" to "Требуется доступ к папкам",
            "permission_desc" to "Для работы на Android 11+ требуется доступ к папке WhatsApp для поиска статусов.",
            "permission_btn" to "Предоставить доступ",
            "dialog_clear_all_title" to "Удалить сохраненные файлы",
            "dialog_clear_all_desc" to "Вы уверены, что хотите удалить ВСЕ загруженные статусы? Это действие необратимо.",
            "dialog_delete" to "Удалить",
            "dialog_cancel" to "Отмена",
            "empty_statuses" to "Статусы не найдены. Сначала посмотрите их в WhatsApp!",
            "empty_downloads" to "Вы еще не сохранили ни одного статуса. Перейдите на Главную и сохраните!"
        ),
        AppLanguage.TURKISH to mapOf(
            "splash_title" to "Durum Kaydedici 2026",
            "splash_loading" to "Medya Motoru Hazırlanıyor...",
            "welcome_title" to "WhatsApp Durum Kaydedici",
            "welcome_desc" to "WhatsApp resim ve videolarını anında kaydedin.",
            "btn_next" to "Sonraki",
            "btn_skip" to "Geç",
            "lang_title" to "Dil Seçin",
            "btn_continue" to "Devam Et",
            "onboarding_title" to "3 Kolay Adımda Kaydet",
            "onboarding_step1_title" to "1. WhatsApp'ı Açın",
            "onboarding_step1_desc" to "Normal şekilde WhatsApp veya WhatsApp Business'ı açın.",
            "onboarding_step2_title" to "2. Duruma Bakın",
            "onboarding_step2_desc" to "Kaydetmek istediğiniz resim veya videonun tamamını izleyin.",
            "onboarding_step3_title" to "3. Uygulamadan Kaydedin",
            "onboarding_step3_desc" to "Buraya geri dönün ve tek bir dokunuşla güvenle indirin.",
            "btn_get_started" to "Başla",
            "tab_images" to "Resimler",
            "tab_videos" to "Videolar",
            "nav_home" to "Ana Sayfa",
            "nav_downloads" to "İndirmeler",
            "nav_settings" to "Ayarlar",
            "search_hint" to "Durum ara...",
            "status_whatsapp" to "WhatsApp",
            "status_whatsapp_business" to "Business",
            "toast_saved" to "Galeriye başarıyla kaydedildi!",
            "toast_save_err" to "Durum kaydedilirken hata oluştu.",
            "toast_deleted" to "Kaydedilen durum silindi.",
            "toast_refreshed" to "Durumlar güncellendi",
            "tutorial_title" to "Nasıl Çalışır",
            "tutorial_step1" to "WhatsApp'a gidin ve kaydetmek istediğiniz duruma bakın.",
            "tutorial_step2" to "Uygulamanın algılayabilmesi için durumun tamamını izleyin.",
            "tutorial_step3" to "Geri dönün ve tek dokunuşla anında indirin.",
            "btn_got_it" to "Anladım",
            "btn_dont_show" to "Bir Daha Gösterme",
            "rating_title" to "Fikriniz Bizim İçin Önemli!",
            "rating_desc" to "Durum Kaydedici ile deneyiminizi bizimle paylaşın.",
            "btn_rate_us" to "Puan Ver",
            "btn_later" to "Sonra",
            "settings_general" to "Genel Ayarlar",
            "settings_auto_save" to "Durumları Otomatik Kaydet",
            "settings_notifications" to "Bildirim Durumu",
            "settings_clear_all" to "Tüm Kayıtlı Dosyaları Temizle",
            "settings_support" to "Destek ve Bilgi",
            "settings_how_to_use" to "Nasıl Kullanılır",
            "settings_privacy" to "Gizlilik Politikası",
            "settings_rate" to "Uygulamayı Puanla",
            "settings_share" to "Arkadaşlarınla Paylaş",
            "settings_footer_desc" to "WhatsApp durumlarını kolayca kaydedin ve indirin. Hiçbir anı kaçırmayın.",
            "settings_version" to "Sürüm 1.0.0",
            "permission_title" to "Depolama Klasörü Erişimi Gerekli",
            "permission_desc" to "Görüntülenen durumları getirmek için Android 11+ sürümlerinde WhatsApp klasörüne izin verilmelidir.",
            "permission_btn" to "Klasör Erişim İzni Ver",
            "dialog_clear_all_title" to "Kayıtlı Dosyaları Temizle",
            "dialog_clear_all_desc" to "Tüm indirilen durumları silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
            "dialog_delete" to "Sil",
            "dialog_cancel" to "İptal",
            "empty_statuses" to "Durum bulunamadı. Önce WhatsApp'ta bazı durumları görün!",
            "empty_downloads" to "Henüz hiçbir durum kaydetmediniz. Ana sayfaya gidin ve kaydedin!"
        )
    )

    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }
}
